# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-15 15:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_auto_20161116_0030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='updated_at',
            field=models.DateTimeField(null=True),
        ),
    ]
